### ISSUE TITLE
Inhaltsverzeichnis ergänzen

### ISSUE THREAD

**Issue by DomenicDev** [0xTimT/HFU-LaTeX-Thesis-Template-English#1]
Zuerst besten Dank für diese tolle Vorlage. Ich habe sie bereits in meiner Bachelorarbeit verwendet und werde sie auch wieder in meiner Masterarbeit verwenden. 

Laut Richtlinien ist das "Inhaltsverzeichnis" Teil des Inhaltsverzeichnisses. Vielleicht lässt sich das noch einbauen?

**Comment by 0xTimT** [comment]
freut mich, dass dir die Vorlage für deine Thesis geholfen hat!

Kannst du mir sagen, wo du das gefunden hast, dass das Inhaltsverzeichnis Teil des Inhaltsverzeichnisses sein soll?
Beim Überfliegen der Richtlinien von Fakultät IN (https://www.hs-furtwangen.de/fileadmin/user_upload/fak_IN/Dokumente/03_Formulare/RichtlinienWissenschaftlicheArbeiten_bearbeitung2020_masu.pdf) habe ich spontan nichts dazu gefunden.

Übersehe ich etwas?

**Comment by 0xTimT** [comment]
Bei genauerem Lesen legt der Satz in Überschrift 2.5 der Richtlinien "Das Inhaltsverzeichnis reflektiert alle Elemente der wissenschaftlichen Arbeit entsprechend Tabelle 3, jedoch nicht das Titelblatt." tatsächlich fest, dass das Inhaltsverzeichnis teil des Inhaltsverzeichnisses sein muss. (da in Tabelle 3 aufgeführt).

Rein logisch finde ich das zwar unsinnig, aber wenn man die offiziellen Vorgaben genau nimmt...

Habe die Vorlage entsprechend geändert, s. commit 17d9607b82c9f41beafc3cf58c27986130a69122
Danke nochmal für den Hinweis :)

**Comment by DomenicDev** [comment]
Danke für deine Rückmeldung! Du hast recht, in der Beschreibung ist es nicht ganz ersichtlich, ob das Inhaltsverzeichnis Teil des Inhaltsverzeichnisses ist. Jedenfalls ist dies der Fall in der offiziellen Word-Vorlage.

Besten Dank für deine Zeit!
